version: "3.7"
services:
  db:
    image: postgres:12
    container_name: EduBridge-DB
    environment:
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: mac1996
      POSTGRES_DB: EduBridge
    ports:
        - "5434:5432"
    volumes:
        - ./db:/var/lib/postgresql/data

